#!/bin/sh 
#
# Configuration for the Vodafone IPTV (vlan 105) / VoIP (vlan 101)
#
# This should only be run once, as the setting will be saved to the router's
# nvram.  The router should be rebooted for the updated config to take effect.
#
#  There are some options:

# 1. To only have the vlan available to the router itself:
# nvram set vlan12ports="0t 8" 
#nvram set vlan12hwname=et0

# 2. To have the vlan available to the router and on the fourth port, e.g
# for plugging the MEO router behind the ASUS router, and only making the 
# vlan12 available to it:

# dupe trunked wan port on port 4
nvram set vlan105ports="0t 8"
nvram set vlan105hwname=et0

nvram set vlan101ports="0t 4 8"
nvram set port4vlans=101
nvram set vlan101hwname=et1


nvram commit
# reboot
